### ISSUE TITLE
Peer nodes are importing baker secret keys

### ISSUE THREAD

**Issue by harryttd** [tqtezos/tezos-k8s#107]
The reasoning behind why peer nodes import baker keys in the first place is to make it convenient for nodes to know about which addresses exist in the private cluster for purposes of transferring tez, etc.

Preferably only public keys should be imported. Not secret keys.

This ticket is more a description of a present fact to keep in mind for future use cases that may come up. An example might be if at some point cluster admins are able to give ssh access to specific nodes within the cluster. Someone with access only to a peer node should not be able to view the secret keys of a baker.

**Comment by nicolasochem** [comment]
Fixed in https://github.com/tqtezos/tezos-k8s/pull/220
