### ISSUE TITLE
improve template generation

### ISSUE THREAD

**Issue by agtilden** [tqtezos/tezos-k8s#12]
current mkchain script just uses python string templates to generate yaml definitons.

use a more widely accepted tool for the job like helm or kustomize

see: https://foghornconsulting.com/2020/06/04/helm-versus-kustomize/

**Comment by itkach** [comment]
Also consider https://tanka.dev/

**Comment by itkach** [comment]
and https://github.com/dhall-lang/dhall-kubernetes

**Comment by itkach** [comment]
and https://github.com/pulumi/pulumi

**Comment by brandisimus** [comment]
It is now Helm.
