### ISSUE TITLE
Allow specifying /etc/tezos/parameters.json in values.yaml files.

### ISSUE THREAD

**Issue by elric1** [tqtezos/tezos-k8s#125]
We should provide a mechanism for specifying the contents of `/etc/tezos/parameters.json` in our values.yaml files. To start the conversation, I'd propose just encoding the parameters directly in YAML as they'd appear in `/etc/tezos/parameters.json` and have the config-generator container fill in defaults for anything that's missing.

**Comment by harryttd** [comment]
closing in favor of https://github.com/tqtezos/tezos-k8s/issues/126
