### ISSUE TITLE
define a storageClass with allowVolumeExpansion

### ISSUE THREAD

**Issue by nicolasochem** [tqtezos/tezos-k8s#172]
By default you cannot resize a PV on EKS

https://docs.aws.amazon.com/eks/latest/userguide/storage-classes.html

It's important to be able to do it on production infra when the chain size reaches the limit and it's not immediately practical to redeploy.

But the storageclass definition is different for each cloud so it needs some minikube/eks forking logic. Since I won't do it straight away, I'm opening a ticket instead.

See also:
https://github.com/midl-dev/tezos-on-gke/blob/master/k8s/tezos-public-node-base/tezos-public-node-stateful-set.yaml#L9

**Comment by orcutt989** [comment]
https://blog.kintone.io/entry/pvc-autoresizer 

@harryttd is here where you wanted this?

**Comment by harryttd** [comment]
I implemented this for AWS volumes in tqinfra https://github.com/tqtezos/tqinfra/pull/31

**Comment by harryttd** [comment]
This belongs in tqinfra
