### ISSUE TITLE
Investigate occasional activate-job errors

### ISSUE THREAD

**Issue by harryttd** [tqtezos/tezos-k8s#18]
I'm noticing that the `activate-job` is occasionally erring. Usually it restarts and the next try works. Other times all restarts fail.

Examples: 

Running cmd similar to `k -n tqtezos1 logs activate-job-2vmh8 -c activate` to retrieve logs.

1. 
```
<<<<4: 500 Internal Server Error
  [ { "kind": "temporary", "id": "failure",
      "msg":
        "(Invalid_argument \"Json_encoding.construct: consequence of bad union\")" } ]
Error:
  (Invalid_argument "Json_encoding.construct: consequence of bad union")
```

2.
```
<<<<2: 500 Internal Server Error
  [ { "kind": "permanent", "id": "proto.006-PsCARTHA.context.storage_error",
      "missing_key": [ "rolls", "owner", "current" ], "function": "copy" } ]
Error:
  Storage error:
    Cannot copy undefined key 'rolls/owner/current'.
```

Seb sent me some code (tezos source code I believe):
```
let () =
  register_error_kind
    `Permanent
    ~id:"context.storage_error"
    ~title: "Storage error (fatal internal error)"
    ~description:
      "An error that should never happen unless something \
       has been deleted or corrupted in the database."
```

3.
Sometimes I see this error:
```
<<<<4: 500 Internal Server Error
  [ { "kind": "temporary", "id": "failure", "msg": "Fitness too low" } ]
Error:
  Fitness too low
```
Seb says he's seen that one very often when trying to activate a protocol on a chain that is already activated. Could be minikube has not removed all the necessary resources/storage after I deleted the namespace and re-applied the yml. This could also be related to the second error where there is deleted and/or corrupted data.

**Comment by harryttd** [comment]
I noticed that even when deleting the tqtezos namespace, it appears that sometimes persistent volumes are not removed. Usually they are deleted along with the rest of the namespace. When the PV's are not removed and I applied the yaml again, I got the "fitness too low error". Which makes sense as the volume is being used which already has an activated protocol stored on it.

**Comment by brandisimus** [comment]
Aryeh please add documentation for this in the Development.md
