### ISSUE TITLE
BCD Indexer: The BCD containers need to share a volume

### ISSUE THREAD

**Issue by harryttd** [tqtezos/tezos-k8s#182]
The BCD containers share some local fs data that needs to be persisted. The volume size should be 1gb. 

This supposedly should fix deployed indexers that stop indexing at certain points.

**Comment by brandisimus** [comment]
Support for BCD indexers is deprecated in k8s. @harryttd do we still need this?

**Comment by harryttd** [comment]
I'm not totally sure. I don't know if there are groups that still want it.

**Comment by brandisimus** [comment]
There are no groups currently that require BCD, I've confirmed with all active projects TQ supports. However there is a chance, however small, that in the future someone (new) would need BCD. But then we'd get new requirements and new ticket.
