### ISSUE TITLE
Allow external access to tezos node

### ISSUE THREAD

**Issue by itkach** [tqtezos/tezos-k8s#22]
External clients and tezos nodes should be able to talk to the node(s) running inside k8s cluster via RPC and/or p2p

**Comment by agtilden** [comment]
p2p access is a TCP passthru

rpc is via HTTP and should be limited to a "safe" subset of the available URLs

**Comment by harryttd** [comment]
Expose your local cluster: https://github.com/tqtezos/tezos-k8s/tree/aryeh/ingress/test-chain#expose-cluster-locally-on-your-lan

**Comment by harryttd** [comment]
We decided a while ago to punt on whitelisting a safe subset of endpoints.

A client can make RPC calls via the RPC Auth mechanism: https://github.com/tqtezos/tezos-k8s/tree/master/rpc-auth.

If Zerotier is being used, they can also make RPC calls directly to Zerotier ip address of the node as long as they join the network on their machine using the Zerotier CLI, and the network admin adds/accepts the user to the network.

P2P is currently implemented just via Zerotier #10
