### ISSUE TITLE
config-generator.py writes to disk then reads from it

### ISSUE THREAD

**Issue by nicolasochem** [tqtezos/tezos-k8s#221]
It has occurred to me while working on #220 that config-generator.py is (1) taking a list of accounts from values.yaml (2) deriving pubkeys and/or hashes from these values (3) writing them in /var/tezos/client for pod use then (4) reading files in /var/tezos/client again for purposes such as writing the genesis pubkey in the config file.

There is no point in writing to disk then reading from it within the same init container. Why not store what we need in an internal object and then distribute data to files in one step?

It's very minor and probably does not need fixing but I want to hold this though in a ticket before I forget.

**Comment by harryttd** [comment]
closed via #223
