### ISSUE TITLE
Allow user to choose CORS headers for public RPC node

### ISSUE THREAD

**Issue by smondet** [tqtezos/tezos-k8s#24]
```
       --cors-header=HEADER
           Header reported by Access-Control-Allow-Headers reported during
           CORS preflighting; may be used multiple times

       --cors-origin=ORIGIN
           CORS origin allowed by the RPC server via
           Access-Control-Allow-Origin; may be used multiple times
```

(shloud also be able to set them in the `config.json`)

**Comment by harryttd** [comment]
This is currently specifiable for every node. You add config.json values in the config section of the node definition: https://github.com/tqtezos/tezos-k8s/blob/d070add62e2f09eacd77ef822babbb9af82aa98b/charts/tezos/values.yaml#L95-L99
