### ISSUE TITLE
remove flextesa dependency

### ISSUE THREAD

**Issue by agtilden** [tqtezos/tezos-k8s#26]
flextesa is used to generate the block value for config.json

this introduces an additional dependency and another docker image download. can the same thing be accomplished with tezos binaries?

**Comment by smondet** [comment]
is this the only use?

```
        run_docker(
            FLEXTESA,
            "flextesa",
            "/tmp:/tmp",
            "vani",
            '""',
            "--seed",
            seed,
            "--first",
            "--machine-readable",
            "csv",
        )
```

I don't know any other tool that can do that OTOH, but is it really needed? maybe you can get users to provide they prefered block-hash/chain-id in a toplevel config file?

Also note that searching the empty-string as vanity hash, means that flextesa is just returning the first attempt for the given seed:

```
            "vani",
            '""',
```

**Comment by smondet** [comment]
so if this remains python _and_ we only care about varying the chain-id deterministically, you just need blake2b and base58 libraries (or the pytezos thing must have that)

**Comment by brandisimus** [comment]
related to removing docker dependency from the chain
