### ISSUE TITLE
move generate-constants to k8s jobs

### ISSUE THREAD

**Issue by nicolasochem** [tqtezos/tezos-k8s#46]
We rely on locally installed docker to generate the constants by running short-lived commands on the tezos and flextesa container. This should mode to kubernetes jobs to reduce the HOWTO requirements.

Mkchain should then funnel the results out of kubernetes safely and back into a file, perhaps with `kubectl cp` or the python sdk equivalent.

**Comment by brandisimus** [comment]
This is related to the docker issues, need to decide whether this is the right approach

**Comment by nicolasochem** [comment]
I made the suggestion to funnel values out because I wanted to preserve the property that the same values.yaml should yield the same account/baker mapping with the same addresses.

Now that we have a mechanism to deterministically derive accounts from names, we can satisfy this property without extracting account keys, so we can drop this requirement.

**Comment by brandisimus** [comment]
Closing the issue as per @nicolasochem above.
