### ISSUE TITLE
Simplify node startup definitions - let node generate identity

### ISSUE THREAD

**Issue by itkach** [tqtezos/tezos-k8s#64]
According to https://tezos.gitlab.io/releases/version-8.html#changelog-version-8-0-rc1, starting with 8.0 rc1 `tezos-node run` now automatically generates identity. `node.yaml` and `bootstrap.yaml` can be now simplified and not check for identity.json themselves

**Comment by brandisimus** [comment]
[node.yaml ](https://github.com/tqtezos/tezos-k8s/blob/4f2d20ede3c28799b2b94b71865768000fbca94d/charts/tezos/templates/node.yaml#L122) still contains this functionality.

**Comment by harryttd** [comment]
@itkach Should we keep in mind that a user would want to use an earlier version of Tezos? We can templatize the key gen then.

**Comment by brandisimus** [comment]
I suggest we park this for a while, and remove the code once 8 is adopted. I'd rather not focus on old versions unless we absolutely have to.

**Comment by itkach** [comment]
>  I'd rather not focus on old versions unless we absolutely have to.

I agree

**Comment by harryttd** [comment]
closed by #117
