### ISSUE TITLE
Research removing docker dependency in mkchain

### ISSUE THREAD

**Issue by brandisimus** [tqtezos/tezos-k8s#89]
Currently using docker to generate keys (tezos docker image) and creating a genesis block hash (in flextessa). This is an akward and unnecessary complication on the pipeline and ideally would be replaced with a simpler solution if possible. This ticket requires research wrt this possibility.

**Comment by brandisimus** [comment]
Related #26, #46

**Comment by harryttd** [comment]
WIP creating block hash without flextesa:

```python
from base58 import b58encode_check
from hashlib import blake2s
​
seed = str.encode(
    "".join(random.choice(string.ascii_uppercase + string.digits) for _ in range(16))
)
​
print(seed)
blake = blake2s(seed)
print(blake.digest_size)
# Prepend letter B
blake = b"\x01\x34" + blake.digest()
print(blake)
print(b58encode_check(blake))
```
The above is based on me talking to Seb and this link https://tezos.stackexchange.com/a/1213/3189. The tezos node accepts the output. Still requires more testing

**Comment by harryttd** [comment]
Links for potentially generating keys without flextesa:

https://github.com/ecadlabs/taquito/search?q=secret
https://github.com/ecadlabs/taquito/blob/6a4e4ab6ac/packages/taquito-signer/src/ed-key.ts

https://github.com/ereOn/csodium
https://github.com/pyca/pynacl/blob/master/INSTALL.rst

https://pytezos.org/_modules/pytezos/crypto.html#Key.generate

**Comment by harryttd** [comment]
Seb mentioned that it may be possible to use `ssh gey gen` which is (almost?) available everywhere to generate keys.

**Comment by harryttd** [comment]
This issue is related to PR #154.
We likely could still remove docker and generate random genesis blocks with `blake2b` and keys via python lib `nacl`. This is currently implemented in [config-generator](https://github.com/tqtezos/tezos-k8s/blob/5bd480c0c9/config-generator/entrypoint.py#L10-L11) thanks to Roland
