### ISSUE TITLE
Enable creation of a baking operation (to join mainnet or otherwise) using k8s toolchain

### ISSUE THREAD

**Issue by brandisimus** [tqtezos/tezos-k8s#97]
#### [Job To Be Done (JTBD)](https://jobs-to-be-done.com/what-is-jobs-to-be-done-fea59c8e39eb) of this functionality:

When an organisation wants to become a participant in the crypto-economic system of Tezos, it would use the same infrastructure toolchain (helm/k8s/docker/etc) as for 'private network' to test, create, monitor and operate an institutional-grade production baking cluster - with high SLAs - in order to maximise the operation availability and thus baking rewards (revenue).

The following scenarios should be possible:

- create a single or multi-node baking set-up and join mainnet
- the same but joining a testnet of customers' choice
- rolling updates of the baking cluster with newly released Tezos software versions

**Comment by brandisimus** [comment]
Depends on remote signing

**Comment by harryttd** [comment]
All scenarios have been covered. I will make a new ticket for rolling updates where new updates may require other steps besides just changing the docker image tag.

Basic remote signing implemented https://github.com/tqtezos/tezos-k8s/issues/218
