### ISSUE TITLE
It should be possible to expand/reduce the number of bakers at run time

### ISSUE THREAD

**Issue by brandisimus** [tqtezos/tezos-k8s#98]
When a private network operator needs to onboard/oboard a 'validator' onto the network it needs to be able to simply 'add'/remove' another baker node to the network at run time and thus to reconfigure the network without rebuilding/restarting everything so to fulfil the SLAs and/or speed up the adjustment process.

**Comment by harryttd** [comment]
I don't understand this. Isn't this just a matter of scaling sts's up or down? @nicolasochem

**Comment by harryttd** [comment]
I am closing this. It sounds like what scaling the statefulset is. Which can be done manually via k9s or the like, or in Helm values.yaml with an install.

**Comment by brandisimus** [comment]
There is a difference in operating parameters between staking a single instance of baker or distributing your stake across multiple bakers. The idea of this ticket was to be able to change the number of bakers without rebuilding the entire network - ie to be able to add/remove the instance after the network was created. @harryttd
